version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  jwt-project:
    image: jwt-project
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "8080:8080"


